### ISSUE TITLE
ActiveRecord::NotNullViolation (PG::NotNullViolation: ERROR:  null value in column "resource_owner_id" of relation "devise_api_tokens" violates not-null constraint

### ISSUE THREAD

**Issue by rega1237** [nejdetkadir/devise-api#11]
Hello everyone, I have an issue setting up this gem, I follow the instructions and when I try to create a new user I got this error (see the title) the resource_owner_id is null, and if you can see the image attached, when the transaction starts the user is created, I will leave here my model and other things, any help I will really appreciate!

## User Model:

![Screenshot from 2023-03-27 20-04-58](https://user-images.githubusercontent.com/58194121/228093554-b8a99c7c-3ab9-48c7-bbc2-c739c011b90d.png)

## Schema:

![Screenshot from 2023-03-27 20-06-21](https://user-images.githubusercontent.com/58194121/228093696-f15c7381-39d4-46ac-b933-f1397b24f47d.png)

![image](https://user-images.githubusercontent.com/58194121/228093734-dfa5183c-6103-4365-a8df-40c93f784cde.png)

## Error:

![Screenshot from 2023-03-27 19-58-27](https://user-images.githubusercontent.com/58194121/228092879-66fb6b27-9656-4621-be67-a44beacbf7ec.png)
![Screenshot from 2023-03-27 19-58-47](https://user-images.githubusercontent.com/58194121/228092889-f3484743-53c1-474c-bddd-6702f987a48f.png)

**Comment by nejdetkadir** [comment]
**resource_owner_id** field is uuid on your devise_api_tokens table, please change column type as your default primary key type

**Comment by rega1237** [comment]
> **resource_owner_id** field is uuid on your devise_api_tokens table, please change column type as your default primary key type

Yeap that works thank you !

**Comment by Mir0ff944** [comment]
I am running into this issue, but cannot seem to resolve it. Could you guys provide more information on how to resolve it please?

**Comment by chridubois** [comment]
Hi,

i've tried to do what you suggest. I've created a new migration : 

`class ChangeUuidColumnType < ActiveRecord::Migration[7.0]
  def change
    change_column :devise_api_tokens, :resource_owner_id, :primary_key
  end
end`

 and I get this error : 

> == 20230529143952 ChangeUuidColumnType: migrating =============================
-- change_column(:devise_api_tokens, :resource_owner_id, :primary_key)
rails aborted!
StandardError: An error has occurred, this and all later migrations canceled:

PG::SyntaxError: ERROR:  syntax error at or near "primary"
LINE 1: ..." ALTER COLUMN "resource_owner_id" TYPE bigserial primary ke...


Did I miss something ?
