### ISSUE TITLE
AbstractController::ActionNotFound: The action 'sign_in' could not be found

### ISSUE THREAD

**Issue by vergil-zhao** [nejdetkadir/devise-api#19]
After defining a customized controller for `TokensController` like the below:
<img width="784" alt="" src="https://user-images.githubusercontent.com/4736661/231232232-47d5d3bb-f85e-45a9-8d0c-3194170fa9dd.png">

And setting the route to the new controller:
<img width="370" alt="" src="https://user-images.githubusercontent.com/4736661/231232325-fda674ac-9358-43cb-8311-cf6fca6b342c.png">

Then it cannot find the sign_in method:
<img width="1324" alt="" src="https://user-images.githubusercontent.com/4736661/231232810-d301fe96-11e8-462e-a36f-dad16ab337d9.png">

But other routes work fine (users/tokens/info, users/tokens/revoke, etc.).

Could you help with that?

**Comment by borisMD24** [comment]
well, your token controller extends Devise::Api::TokensController

i did it that way : 
`
def sign_in
       super()
end
`

**Comment by nejdetkadir** [comment]
@vergil-zhao did u fixed it?
