### ISSUE TITLE
ActiveRecord::NotNullViolation in Devise::Api::TokensController#sign_in

### ISSUE THREAD

**Issue by dafal** [nejdetkadir/devise-api#20]
👋 I wanted to give a try to this gem but when I try to sign_in I get this error:

ActiveRecord::NotNullViolation in Devise::Api::TokensController#sign_in
PG::NotNullViolation: ERROR: null value in column "resource_owner_id" of relation "devise_api_tokens" violates not-null constraint 
DETAIL: Failing row contains (21, User, null, 8rUvzXixhsNeyypZBWjsm3-aQszFgrBKm2EngYsy1S24PGsYSFrwD6Cxh3Hu, KuxVpFjzq8vopMMzztR3f7i47LgsST33XL44tAzCVA19xCnxZGLztgHwdTDk, 3600, null, null, 2023-04-12 09:50:42.582888, 2023-04-12 09:50:42.582888).

I tried to debug with ChatGPT without success, I can't find where this ressource_owner_id got lost...

**Comment by vergil-zhao** [comment]
Check issue #11

> resource_owner_id field is uuid on your devise_api_tokens table, please change column type as your default primary key type

**Comment by dafal** [comment]
Oups, I did not see this resolved issue. Sorry for this. 😇  Btw what I first tested was to remove the type but it did not work.  Forcing it to the default type (biting in my case) solves indeed the issue.  Thank you  for the help and the great gem !
