### ISSUE TITLE
Forgot Password Endpoint

### ISSUE THREAD

**Issue by yanismydj** [nejdetkadir/devise-api#35]
Has anyone tried to set up "Forgot Password"/"Reset Password" functionality with devise-api?

**Comment by emilzonj** [comment]
> Has anyone tried to set up "Forgot Password"/"Reset Password" functionality with devise-api?

I think, you could use the devise passwords controller for that.

**Comment by seyhak** [comment]
> Has anyone tried to set up "Forgot Password"/"Reset Password" functionality with devise-api?

I used devise controllers for that
