### ISSUE TITLE
Confirmation email redirect to a certain host

### ISSUE THREAD

**Issue by prp-e** [nejdetkadir/devise-api#37]
Greetings. 

I implemented devise's email confirmation on my app, which is an _api only_ app and I also use `devise-api` in order to bring it to life. 
The problem is when I confirm the account, it goes to `localhost:3001/users/sing_in` which is not there. I just want it to send my user back to the index page of my site. I am using this method:

```ruby
class ConfirmationsController < Devise::ConfirmationsController

    def new
        super
      end
    
      def create
        super
      end
    
      def show
        self.resource = resource_class.confirm_by_token(params[:confirmation_token])
    
        if resource.errors.empty?
          set_flash_message(:notice, :confirmed) if is_navigational_format?
          sign_in(resource_name, resource)
          respond_with_navigational(resource){ redirect_to('https://example.com/page', allow_other_host: true) }
        else
          false
        end
      end

end
```

But as I said earlier, it goes to `/users/sign_in` to my app which does not exist.

**Comment by nejdetkadir** [comment]
good question, maybe usefull callbacks will help to u, you can check from [here](https://github.com/nejdetkadir/devise-api?tab=readme-ov-file#configuration)
