### ISSUE TITLE
Incompatible with Mongoid ORM 

### ISSUE THREAD

**Issue by merouaneamqor** [nejdetkadir/devise-api#39]
```ruby
Devise.setup do |config|
  config.mailer_sender = 'please-change-me-at-config-initializers-devise@example.com'
  require 'devise/orm/mongoid'
  config.case_insensitive_keys = [:email]
  config.strip_whitespace_keys = [:email]
  config.skip_session_storage = [:http_auth]
  config.reconfirmable = true
  config.expire_all_remember_me_on_sign_out = true
  config.responder.error_status = :unprocessable_entity
  config.responder.redirect_status = :see_other
end
```

ActiveRecord::ConnectionNotEstablished at /api/v1/users/tokens/sign_in
======================================================================

No connection pool for 'ActiveRecord::Base' found.

> To access an interactive console with this error, point your browser to: /__better_errors

activerecord (7.0.8) lib/active_record/connection_adapters/abstract/connection_handler.rb, line 208
---------------------------------------------------------------------------------------------------

``` ruby
  203               message = "No connection pool for '#{spec_name}' found for the '#{role}' role."
  204             else
  205               message = "No connection pool for '#{spec_name}' found."
  206             end
  207   
> 208             raise ConnectionNotEstablished, message
  209           end
  210   
  211           pool.connection
  212         end
  213   
```

App backtrace
-------------

Full backtrace
--------------

 - activerecord (7.0.8) lib/active_record/connection_adapters/abstract/connection_handler.rb:208:in `retrieve_connection'
 - activerecord (7.0.8) lib/active_record/connection_handling.rb:313:in `retrieve_connection'
 - activerecord (7.0.8) lib/active_record/connection_handling.rb:280:in `connection'
 - activerecord (7.0.8) lib/active_record/model_schema.rb:407:in `table_exists?'
 - activerecord (7.0.8) lib/active_record/attribute_methods.rb:163:in `attribute_names'
 - actionpack (7.0.8) lib/action_controller/metal/params_wrapper.rb:118:in `block in include'
 - /usr/local/lib/ruby/3.2.0/mutex_m.rb:79:in `mu_synchronize'
 - actionpack (7.0.8) lib/action_controller/metal/params_wrapper.rb:112:in `include'
 - actionpack (7.0.8) lib/action_controller/metal/params_wrapper.rb:278:in `_extract_parameters'
 - actionpack (7.0.8) lib/action_controller/metal/params_wrapper.rb:274:in `_wrap_parameters'
 - actionpack (7.0.8) lib/action_controller/metal/params_wrapper.rb:300:in `_perform_parameter_wrapping'
 - actionpack (7.0.8) lib/action_controller/metal/params_wrapper.rb:258:in `process_action'
 - mongoid (8.1.4) lib/mongoid/railties/controller_runtime.rb:21:in `process_action'
 - actionpack (7.0.8) lib/abstract_controller/base.rb:151:in `process'
 - actionview (7.0.8) lib/action_view/rendering.rb:39:in `process'
 - actionpack (7.0.8) lib/action_controller/metal.rb:188:in `dispatch'
 - actionpack (7.0.8) lib/action_controller/metal.rb:251:in `dispatch'
 - actionpack (7.0.8) lib/action_dispatch/routing/route_set.rb:49:in `dispatch'
 - actionpack (7.0.8) lib/action_dispatch/routing/route_set.rb:32:in `serve'
 - actionpack (7.0.8) lib/action_dispatch/routing/mapper.rb:18:in `block in <class:Constraints>'
 - actionpack (7.0.8) lib/action_dispatch/routing/mapper.rb:48:in `serve'
 - actionpack (7.0.8) lib/action_dispatch/journey/router.rb:50:in `block in serve'
 - actionpack (7.0.8) lib/action_dispatch/journey/router.rb:32:in `serve'
 - actionpack (7.0.8) lib/action_dispatch/routing/route_set.rb:852:in `call'
 - mongo (2.19.3) lib/mongo/query_cache.rb:278:in `block in call'
 - mongo (2.19.3) lib/mongo/query_cache.rb:52:in `cache'
 - mongo (2.19.3) lib/mongo/query_cache.rb:277:in `call'
 - warden (1.2.9) lib/warden/manager.rb:36:in `block in call'
 - warden (1.2.9) lib/warden/manager.rb:34:in `call'
 - rack (2.2.8) lib/rack/tempfile_reaper.rb:15:in `call'
 - rack (2.2.8) lib/rack/etag.rb:27:in `call'
 - rack (2.2.8) lib/rack/conditional_get.rb:40:in `call'
 - rack (2.2.8) lib/rack/head.rb:12:in `call'
 - actionpack (7.0.8) lib/action_dispatch/http/permissions_policy.rb:38:in `call'
 - actionpack (7.0.8) lib/action_dispatch/http/content_security_policy.rb:36:in `call'
 - rack (2.2.8) lib/rack/session/abstract/id.rb:266:in `context'
 - rack (2.2.8) lib/rack/session/abstract/id.rb:260:in `call'
 - actionpack (7.0.8) lib/action_dispatch/middleware/cookies.rb:704:in `call'
 - actionpack (7.0.8) lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
 - activesupport (7.0.8) lib/active_support/callbacks.rb:99:in `run_callbacks'
 - actionpack (7.0.8) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
 - actionpack (7.0.8) lib/action_dispatch/middleware/executor.rb:14:in `call'
 - actionpack (7.0.8) lib/action_dispatch/middleware/actionable_exceptions.rb:17:in `call'
 - better_errors (2.10.1) lib/better_errors/middleware.rb:87:in `protected_app_call'
 - better_errors (2.10.1) lib/better_errors/middleware.rb:82:in `better_errors_call'
 - better_errors (2.10.1) lib/better_errors/middleware.rb:60:in `call'
 - actionpack (7.0.8) lib/action_dispatch/middleware/debug_exceptions.rb:28:in `call'
 - web-console (4.2.1) lib/web_console/middleware.rb:132:in `call_app'
 - web-console (4.2.1) lib/web_console/middleware.rb:28:in `block in call'
 - web-console (4.2.1) lib/web_console/middleware.rb:17:in `call'
 - actionpack (7.0.8) lib/action_dispatch/middleware/show_exceptions.rb:29:in `call'
 - railties (7.0.8) lib/rails/rack/logger.rb:40:in `call_app'
 - railties (7.0.8) lib/rails/rack/logger.rb:25:in `block in call'
 - activesupport (7.0.8) lib/active_support/tagged_logging.rb:99:in `block in tagged'
 - activesupport (7.0.8) lib/active_support/tagged_logging.rb:37:in `tagged'
 - activesupport (7.0.8) lib/active_support/tagged_logging.rb:99:in `tagged'
 - railties (7.0.8) lib/rails/rack/logger.rb:25:in `call'
 - sprockets-rails (3.4.2) lib/sprockets/rails/quiet_assets.rb:13:in `call'
 - actionpack (7.0.8) lib/action_dispatch/middleware/remote_ip.rb:93:in `call'
 - request_store (1.5.1) lib/request_store/middleware.rb:19:in `call'
 - actionpack (7.0.8) lib/action_dispatch/middleware/request_id.rb:26:in `call'
 - rack (2.2.8) lib/rack/method_override.rb:24:in `call'
 - rack (2.2.8) lib/rack/runtime.rb:22:in `call'
 - activesupport (7.0.8) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
 - actionpack (7.0.8) lib/action_dispatch/middleware/server_timing.rb:61:in `block in call'
 - actionpack (7.0.8) lib/action_dispatch/middleware/server_timing.rb:26:in `collect_events'
 - actionpack (7.0.8) lib/action_dispatch/middleware/server_timing.rb:60:in `call'
 - actionpack (7.0.8) lib/action_dispatch/middleware/executor.rb:14:in `call'
 - actionpack (7.0.8) lib/action_dispatch/middleware/static.rb:23:in `call'
 - rack (2.2.8) lib/rack/sendfile.rb:110:in `call'
 - actionpack (7.0.8) lib/action_dispatch/middleware/host_authorization.rb:138:in `call'
 - rack-cors (2.0.1) lib/rack/cors.rb:102:in `call'
 - railties (7.0.8) lib/rails/engine.rb:530:in `call'
 - puma (6.4.2) lib/puma/configuration.rb:272:in `call'
 - puma (6.4.2) lib/puma/request.rb:100:in `block in handle_request'
 - puma (6.4.2) lib/puma/thread_pool.rb:378:in `with_force_shutdown'
 - puma (6.4.2) lib/puma/request.rb:99:in `handle_request'
 - puma (6.4.2) lib/puma/server.rb:464:in `process_client'
 - puma (6.4.2) lib/puma/server.rb:245:in `block in run'
 - puma (6.4.2) lib/puma/thread_pool.rb:155:in `block in spawn_thread'

**Comment by t3ndai** [comment]
Yeah mongoid didn't work for me with devise_api . This is for Rails 8
