### ISSUE TITLE
Use authentication_keys for resource lookup instead of static email field

### ISSUE THREAD

**Issue by zhaknafein** [nejdetkadir/devise-api#40]
The Devise gem allows to use different authentication_keys instead of the "email" field.
This change (zhaknafein/devise-api@bb8057994632c93db74ab5ba006e5b81f56479b3) will make devise-api follow the same configuration as Devise.
Sorry for the missing translations and tests, i accept suggestions on how to replace the "email" word everywhere :)

**Comment by federicokeen** [comment]
Hello, I'm hitting the same issue and this would fix it. 👍 for the fix, those parameters if I understood correctly are already sanitized by the method sign_in_params, could simply pass params.
