### ISSUE TITLE
Support for both Api and webapp

### ISSUE THREAD

**Issue by ausangshukla** [nejdetkadir/devise-api#41]
1. I have an existing web app with devise, and user login via a UI
2. I want to enable APIs for the existing codebase
3. Does this gem support both simultaneously?
4. How can I set the current_user if the authentication is via devise-api gem ?

Thanks in advance

**Comment by ausangshukla** [comment]
For those looking to do this, here is what Ive done to make it work

```
def authenticate_user!
    if request.headers['Authorization'].present?
      authenticate_devise_api_token!
      @current_user = current_devise_api_user
    else
      super
    end
  end

  def verify_authenticity_token
    super if request.headers['Authorization'].blank? 
  end

```

**Comment by nejdetkadir** [comment]
> Does this gem support both simultaneously?

yes you can use this gem with your existing web app. Just you need to create some helpers like already sent. 🙌
