### ISSUE TITLE
Can I login or signup with attribute other than email like username?

### ISSUE THREAD

**Issue by Sovaid-Shah** [nejdetkadir/devise-api#44]
I want to be able to login using a username or an email whatever the user chooses. I want conditions that the user I pass a single field like login in the request API parameters and the user model returns first user that matches the values either in username or email.

**Comment by nejdetkadir** [comment]
you may right, you contribute to this gem for this functionality @Sovaid-Shah :)

**Comment by zhaknafein** [comment]
As mentioned in #40, i have submitted a PR to fix this request.

**Comment by nejdetkadir** [comment]
#40 merged, you can use now @Sovaid-Shah 🙌🏻
